### ISSUE TITLE
CTXC COİN 1 USD ?

### ISSUE THREAD

**Issue by bleade06** [CortexFoundation/CortexTheseus#1128]
VERY INCOMPATIBLE SITUATION, Dropped From $1. WE ARE WAITING TO MAKE $1 AGAIN WITH MY TEAM FRIENDS. I THINK EVERYONE KNOWS IT AND IT SHOULD BE $1 AGAIN

**Comment by tfdxl** [comment]
Forget it!

**Comment by tfdxl** [comment]
Garbage coin!!! This project was created by Chinese people.They just want to cheat and make hot money.
