### ISSUE TITLE
build cmd tool fail

### ISSUE THREAD

**Issue by steinselite** [CortexFoundation/CortexTheseus#1161]
When build the generator abigen, go install(or build) the cmd/abigen will fail due to missing the torrentfs entry.
The problem is why the torrentfs is essential when we just want to get the abigen tool to generator contract abi?

**Comment by ucwong** [comment]
try to use ```make abigen```

**Comment by steinselite** [comment]
if i use the make abigen:
<img width="639" alt="Screen Shot 2022-01-19 at 7 18 52 PM" src="https://user-images.githubusercontent.com/69792300/150120198-c2ea9584-3cb6-41b1-a620-e9794233773f.png">

**Comment by ucwong** [comment]
https://github.com/CortexFoundation/CortexTheseus#ubuntu
Check the env installation
