### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by AlexSpain** [CortexFoundation/CortexTheseus#1841]
make[1]: Leaving directory '/mine/CortexTheseus/cvm-runtime'
ln -sfn /mine/CortexTheseus/cvm-runtime/build/libcvm_runtime.so plugins/libcvm_runtime.so
build/env.sh go run build/ci.go install ./cmd/cortex
>>> /usr/local/go/bin/go build -ldflags -X main.gitCommit=d069cbdd6874650c464df5f47920cd7dba84bbf7 -X main.gitDate=20231206 -extldflags -Wl,-z,stack-size=0x800000 -trimpath -v -o /mine/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/build/bin/cortex ./cmd/cortex
vendor/github.com/cockroachdb/pebble/compaction.go:9:2: cannot find package "cmp" in any of:
        /mine/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/cmp (vendor tree)
        /usr/local/go/src/cmp (from $GOROOT)
        /mine/CortexTheseus/build/_workspace/src/cmp (from $GOPATH)
vendor/github.com/kataras/golog/integration.go:5:2: cannot find package "log/slog" in any of:
        /mine/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/log/slog (vendor tree)
        /usr/local/go/src/log/slog (from $GOROOT)
        /mine/CortexTheseus/build/_workspace/src/log/slog (from $GOPATH)
vendor/github.com/cockroachdb/pebble/vfs/mem_fs.go:13:2: cannot find package "slices" in any of:
        /mine/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/slices (vendor tree)
        /usr/local/go/src/slices (from $GOROOT)
        /mine/CortexTheseus/build/_workspace/src/slices (from $GOPATH)
util.go:47: exit status 1
exit status 1
make: *** [Makefile:47: cortex_cpu] Error 1

**Comment by ucwong** [comment]
Please try the latest verson fo Golang 

https://go.dev/dl/
