### ISSUE TITLE
CVM crash

### ISSUE THREAD

**Issue by AlexSpain** [CortexFoundation/CortexTheseus#213]
Hi,

Trying to run node at dedicated server Ubuntu 16.04 x64.
Then I run cvm.sh
and at other screen run node.sh

cvm.sh screen have this error every time:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa61f2]

goroutine 67 [running]:
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).lock(0x0)
        /mine2/cortex2_src/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1314 +0x22
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0x230c279a09e0bd9d, 0x7b53acb0acc0ded5, 0x275cb30f, 0x184bea0, 0xc4201f7b60, 0x0, 0xc420396e00)
        /mine2/cortex2_src/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1016 +0x46
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0xc4202065b0, 0x0, 0x0, 0x0, 0x0)
        /mine2/cortex2_src/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1043 +0x88
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).AddInfoHash(0xc4202e0000, 0x230c279a09e0bd9d, 0x7b53acb0acc0ded5, 0x275cb30f, 0x80000)
        /mine2/cortex2_src/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:472 +0x6be
created by github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).mainLoop
        /mine2/cortex2_src/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:588 +0x342

**Comment by ucwong** [comment]
try to clean your .cortex/storage path then run again
or run ./start.sh

**Comment by AlexSpain** [comment]
INFO [08-06|11:09:08.828] Imported new chain segment               blocks=277 txs=32 mgas=2.774 elapsed=72.180ms mgasps=38.431 tps=18.293 number=455    hash=7496cb…0a08e7 age=1mo1w3d dirty=155.41KiB
INFO [08-06|11:09:08.835] Upload OK                                address=0x11179BAd7FAeb989E079624eE1650fEb9bA27906 waiting=100
INFO [08-06|11:09:08.842] Upload OK                                address=0x5935A0e8FD2Ed29b6ae648e838bE6924B8c877c3 waiting=100
WARN [08-06|11:09:08.869] VM returned with error                   err="Kernel runtime error" number=578    from=0x07E6a86d4C2d2013446Ff557BE941dcda3dc843D
WARN [08-06|11:09:08.869] Downloading ... ...                      Number=578 hash=9a4778…3843da
WARN [08-06|11:09:17.511] remote infer: request response failed    error="Post http://localhost:4321/: dial tcp 127.0.0.1:4321: connect: connection refused"
WARN [08-06|11:09:17.511] VM returned with error                   err="Kernel runtime error" number=578    from=0x07E6a86d4C2d2013446Ff557BE941dcda3dc843D

**Comment by ucwong** [comment]
It is ok now, just wait for cvm downloading AI model

**Comment by ucwong** [comment]
If it stuck long time for '"Kernel runtime error' , just ctrl-c stop the process and start again

**Comment by AlexSpain** [comment]
is every time same error

**Comment by AlexSpain** [comment]
I just trying to run node for mining pool test with no luck
./build/bin/cortex --infer.devicetype=remote://localhost:4321  --rpc --verbosity 4 --rpcaddr "0.0.0.0" --rpcport 30089 --rpcapi web3,eth,ctx,miner,net,txpool --maxpeers 64 --nat extip:0.0.0.0 --unlock="0x274a551c37473bf1575007487b4ea86f67d43928" --password="/root/.walletpass" --allow-insecure-unlock

**Comment by AlexSpain** [comment]
also is any documentation for cortex rpc?

**Comment by ucwong** [comment]
--infer.devicetype=remote://localhost:4321 if u use this flag , have to make sure cvm service is running

**Comment by ucwong** [comment]
or --infer.devicetype=cpu

**Comment by AlexSpain** [comment]
./cvm.sh
INFO [10-21|05:41:25.546] path                                     path=/root/.cortex ipc=cortex.ipc
INFO [10-21|05:41:25.546] SetTorrentFsConfig                       IPCPath=/root/.cortex/cortex.ipc
INFO [10-21|05:41:25.546] cvmServer                                torrentfs.Config="{Port:30090 DataDir:/root/.cortex/storage RpcURI: IpcPath:/root/.cortex/cortex.ipc DisableUTP:true DisableDHT:false DefaultTrackers:[http://47.91.91.217:5008/announce http://47.74.1.234:5008/announce http://47.88.7.24:5008/announce http://47.91.43.70:5008/announce http://47.91.106.117:5008/announce http://47.91.147.37:5008/announce http://47.89.178.175:5008/announce http://47.88.214.96:5008/announce http://47.93.158.68:5008/announce http://torrent.cortexlabs.ai:5008/announce http://127.0.0.1:5008/announce] BoostNodes:[http://storage.cortexlabs.ai:7881] SyncMode:full MaxSeedingNum:640 MaxActiveNum:400}" StorageDirFlag.Name=/root/.cortex/storage ipc path=/root/.cortex/cortex.ipc
INFO [10-21|05:41:25.546] Initialising Torrent FS
INFO [10-21|05:41:25.546] Torrent file storage initialized
INFO [10-21|05:41:25.546] Torrent client listening on              addr=:0
INFO [10-21|05:41:25.546] Torrent client configuration             config="&{DataDir:/root/.cortex/storage ListenHost:0xf6c590 ListenPort:0 NoDefaultPortForwarding:false DisableTrackers:false DisablePEX:false NoDHT:false DhtStartingNodes:0xeaa440 NoUpload:false DisableAggressiveUpload:false Seed:true UploadRateLimiter:0xc4200b6fa0 DownloadRateLimiter:0xc4200b6fa0 PeerID: DisableUTP:true DisableTCP:false DefaultStorage:<nil> HeaderObfuscationPolicy:{RequirePreferred:false Preferred:true} CryptoProvides:3 CryptoSelector:0xf23380 ProxyURL: IPBlocklist:<nil> DisableIPv6:false DisableIPv4:false DisableIPv4Peers:false Debug:false Logger:{LoggerImpl:{W:0xc4200b4010 Fmt:0xeb7f10}} HTTPProxy:<nil> HTTPUserAgent:Cortex ExtendedHandshakeClientVersion:1.6.0-stable Bep20:-GT0002- NominalDialTimeout:20s MinDialTimeout:3s EstablishedConnsPerTorrent:2 HalfOpenConnsPerTorrent:1 TorrentPeersHighWater:500 TorrentPeersLowWater:50 HandshakesTimeout:4s PublicIp4:<nil> PublicIp6:<nil> DisableAcceptRateLimiting:false dropDuplicatePeerIds:false ConnTracker:0xc420322510 DHTOnQuery:<nil>}"
ERROR[10-21|05:41:25.547] Error while create torrent client        err="subsequent listen: listen tcp6 :34624: socket: address family not supported by protocol"
INFO [10-21|05:41:25.547] Tracker list                             trackers="[http://47.91.91.217:5008/announce http://47.74.1.234:5008/announce http://47.88.7.24:5008/announce http://47.91.43.70:5008/announce http://47.91.106.117:5008/announce http://47.91.147.37:5008/announce http://47.89.178.175:5008/announce http://47.88.214.96:5008/announce http://47.93.158.68:5008/announce http://torrent.cortexlabs.ai:5008/announce http://127.0.0.1:5008/announce]"
INFO [10-21|05:41:25.547] Torrent client initialized
INFO [10-21|05:41:25.547] Torrent manager initialized
INFO [10-21|05:41:25.547] Torrent monitor starting                 torrentfs="&{config:0xc420322090 history:0xc4202d1480 monitor:0xc4200f6630}"
INFO [10-21|05:41:25.548] Initialising Synapse Engine              Cache Disabled=false
INFO [10-21|05:41:25.548] Initilized inference server with synapse engine config="{IsNotCache:false DeviceType:cpu DeviceId:0 IsRemoteInfer:false InferURI: Debug:false MaxMemoryUsage:4294967296 Storagefs:0xc4202d1840}"
INFO [10-21|05:41:25.548] Http Server Listen on 0.0.0.0:4321
INFO [10-21|05:41:28.548] Validate Torrent FS Storage              last IPC listen number=343511 end=0 latest=343511
INFO [10-21|05:41:28.550] Validate Torrent FS Storage ended        last IPC listen number=343511 end=0 latest=343511
INFO [10-21|05:41:28.551] Torrent fs validation passed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4b622]

goroutine 32 [running]:
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).lock(0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1360 +0x22
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0x1758dc0, 0xc4200abf80, 0x0, 0xc42005ed00)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1060 +0x46
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0xc4200db110, 0x0, 0x0, 0x0, 0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1087 +0x88
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).AddInfoHash(0xc4203b02a0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0xf4240)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:490 +0x68b
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).mainLoop(0xc4203b02a0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:622 +0x349
created by github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).Start
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:600 +0x63
