### ISSUE TITLE
Error while create torrent client

### ISSUE THREAD

**Issue by AlexSpain** [CortexFoundation/CortexTheseus#219]
./cvm.sh

ERROR[08-21|22:36:53.249] Error while create torrent client        err="subsequent listen: listen tcp6 :22654: socket: address family not supported by protocol"

**Comment by ucwong** [comment]
Check the settings of your local router or u can provide more details

**Comment by AlexSpain** [comment]
> Check the settings of your local router or u can provide more details

Ubuntu server not have IPv6 enabled.

**Comment by AlexSpain** [comment]
Hi. Can you look this problem please

**Comment by AlexSpain** [comment]
.[32mINFO .[0m[10-19|15:57:43.331] Torrent fs validation passed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4b622]

goroutine 26 [running]:
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).lock(0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1360 +0x22
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0x1758dc0, 0xc420293350, 0x0, 0xc420063d00)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1060 +0x46
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0xc4201c6230, 0x0, 0x0, 0x0, 0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1087 +0x88
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).AddInfoHash(0xc4203262a0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0xf4240)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:490 +0x68b
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).mainLoop(0xc4203262a0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:622 +0x349
created by github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).Start
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:600 +0x63

**Comment by ucwong** [comment]
Try to use the latest version and clean the storage path.
