### ISSUE TITLE
Cortex hasher implementation go

### ISSUE THREAD

**Issue by AlexSpain** [CortexFoundation/CortexTheseus#220]
Hi.

Can you help with Go implementation of Cortex Share and Block validation?

Thank you.

**Comment by AlexSpain** [comment]
Please, can you share hash verification from official pools?

**Comment by liqingnz** [comment]
You'll have to work it out yourself =P
Please use the specification as reference.

**Comment by AlexSpain** [comment]
@ucwong can you help me please?

**Comment by AlexSpain** [comment]
var mainnetcfg = cuckoo.Config{}
var hasher = cuckoo.New(mainnetcfg)
but it not work
var sol = new(types.BlockSolution)
b, err := hex.DecodeString(params[2][2:])
if err != nil {
log.Printf("Bad sol (#1) from %v@%v", login, ip)
return false, false
}
every time return error

**Comment by AlexSpain** [comment]
any help please?

**Comment by ucwong** [comment]
What does params[2] look like? u can print params[2] out

**Comment by AlexSpain** [comment]
param[2]
0x007c1bb30120746a01472c08035790da04893a020563bc7505b392e205f7e3fc06530e7807b8b5680ea233151022495713a7008a14da1f5416c3e70a17f919611912b0a61b36bc901c304edf1c419e941fd8c9592011edf321eaefc52490
087f28b03f6d29d8b7852d12a04b2d37fe3a2dfcca292e60f8e72e67bd312f61e851367366b8369c46f53753bc16390f9f833ab9702d3c7afefb3d10d4443e6cfec43ec1633a3f0f2884

**Comment by AlexSpain** [comment]
))))))))) good help 1 time in month

**Comment by AlexSpain** [comment]
Why you close mate?
