### ISSUE TITLE
Cortex CVM takes up too many ports.

### ISSUE THREAD

**Issue by BetaBeauty** [CortexFoundation/CortexTheseus#228]
I found that the cvm subprocess creates lots of connections with other nodes while running cortex full-node in my machine, and it's up to 130 thousand without limit which leads to no more succeed socket established.

It's terrible that I cannot do anything once a cortex node is running. Any helpful method, or may I set some flags to limit the connections?

**Comment by ucwong** [comment]
I think it should be better if we use http trackers only

**Comment by ucwong** [comment]
If too many tw connections, u can try as below
vim /etc/sysctl.conf
and add
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_fin_timeout = 30

save & sysctl -p

**Comment by ucwong** [comment]
running the latest version, i think it has been fixed now

**Comment by BetaBeauty** [comment]
The problem has been solved, thanks.
