### ISSUE TITLE
Error: invalid gas used (remote: 1672199 local: 2494892)

### ISSUE THREAD

**Issue by AlexSpain** [CortexFoundation/CortexTheseus#229]
ERROR[10-18|16:36:28.615]
########## BAD BLOCK #########
Chain config: {ChainID: 21 Homestead: 0 DAO: 0 DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 PetersburgBlock: 0 Istanbul: <nil> Engine: cuckoo}

Number: 343445
Hash: 0xbe4af4ea827268db4a93ac81b7d908590543dd3053d445bac7f9eb77db160632
        &{[] 0 2494892 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [73 5 47 99 187 8 149 115 235 198 84 195 203 52 140 10 51 127 154 221 31 78 133 214 126 20 10 14 87 197 79 110] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 2494892}

Error: invalid gas used (remote: 1672199 local: 2494892)
##############################

https://cerebro.cortexlabs.ai/#/block/343445

**Comment by ucwong** [comment]
Make sure the mining node have the ai model used for inference

**Comment by AlexSpain** [comment]
cvm crash every time, what you mean ai model?

**Comment by ucwong** [comment]
clean your storage path and try again

**Comment by AlexSpain** [comment]
Yes we try to Clean and sync again. Every time this issue.

**Comment by AlexSpain** [comment]
please look block explorer, this blocks have anomaly wrong Endorphin Used

**Comment by AlexSpain** [comment]
> Make sure the mining node have the ai model used for inference

What you mean? How I can check this? Thank you

**Comment by AlexSpain** [comment]
Node stuck at block 350954

########## BAD BLOCK #########
Chain config: {ChainID: 21 Homestead: 0 DAO: 0 DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constanti

Number: 350954
Hash: 0x3da6cac033f3614c7cf8a1182af133e9f7b813c07fafc53cd65651aaec56424e
        &{[] 0 3485098 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        &{[] 1 3506098 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        &{[] 1 3527098 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0


Error: invalid gas used (remote: 2377792 local: 3527098)
##############################

**Comment by AlexSpain** [comment]
Help please

**Comment by AlexSpain** [comment]
I not have IPv6 so torrentfs now work properly -  I think is the problem
