### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by frode88** [CortexFoundation/CortexTheseus#241]
Hi.
How to fix this issue? and there is nativ cpu miner?
![Skjermbilde](https://user-images.githubusercontent.com/22121200/69164131-b3e7dd00-0aef-11ea-95cd-7aad67d0f12f.PNG)

**Comment by ucwong** [comment]
could you show more details

**Comment by frode88** [comment]
Hi. Yes- I run the node with ./build/bin/cortex --infer.devicetype=remote://140.xx.0.xx:4321 --rpc --rpcaddr 140.xx.0.xx --rpcport 8545 --mine --miner.threads 1

![Skjermbilde](https://user-images.githubusercontent.com/22121200/69164942-19889900-0af1-11ea-93b1-30234461928c.PNG)

**Comment by ucwong** [comment]
How about your memory size

**Comment by ucwong** [comment]
Make sure you have 11GB memory size at least

**Comment by frode88** [comment]
Hi. I have 16G mem. shouldn be issue..

**Comment by frode88** [comment]
even tested on 32G mem and 8 core cpu and done ulimit -c unlimited - still same issue

**Comment by zkh2018** [comment]
> Hi. Yes- I run the node with ./build/bin/cortex --infer.devicetype=remote://140.xx.0.xx:4321 --rpc --rpcaddr 140.xx.0.xx --rpcport 8545 --mine --miner.threads 1
> 
> ![Skjermbilde](https://user-images.githubusercontent.com/22121200/69164942-19889900-0af1-11ea-93b1-30234461928c.PNG)

The node does not support cpu mine now. 
If you want to mine through node, you have to use "--mine --miner.cuda --miner.devices 0/(other nvidia gpu id) --miner.threads 1" .

**Comment by frode88** [comment]
@zkh2018 Hi. Last Q.
What about mining with node outside the home network? Node in VPS and rigs home?

I use this but node dont allow miner to connect.

./build/bin/cortex --infer.devicetype=remote://78.141.201.xxx:4321 --rpc --rpcaddr 78.141.201.xxx --rpcport 8545 --mine --miner.threads 1

**Comment by frode88** [comment]
Guys Please. Tell how to start the node and mine with my rigs please.  Have the node to be on same mining rig? have to be a way to remote mine.

**Comment by ucwong** [comment]
U should have a 1080ti for a solo mining because cpu is too slow to mine now.
If you want to connect a mining pool to join a union mining please go to  http://cortexmint.com to visit the tutorial

**Comment by frode88** [comment]
Hi. Im not trying to mine with CPU.
1. I have a node on VPS
2. I have a rig with 2080TI

All i want to my rigs to connect to the Node on VPS. 
I start the Node and point my rigs to IP adress and port of the node. The miner connect and disconnet.
This is the line i use to start the Node 
(./build/bin/cortex --infer.devicetype=remote://0.0.0.0:4321 --rpc --rpcaddr=0.0.0.0 --rpcport=8545 --mine
)

**Comment by ucwong** [comment]
I think the remote miner only for mining pool with stratum protocol

**Comment by frode88** [comment]
> I think the remote miner only for mining pool with stratum protocol

Can you check that out? I use dev miner.aka pool miner.

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/69255257-78820700-0bf2-11ea-9ced-078cd36029a3.png)

**Comment by frode88** [comment]
i dont think you understand me. thank you anyway.

**Comment by frode88** [comment]
I think i found the issue. When i build it and try to (export LD_LIBRARY_PATH=$PWD/infernet/build/cpu/:$PWD/infernet/build/gpu:$LD_LIBRARY_PATH)

but there is no gpu folder... at infernet/build/gpu

**Comment by ucwong** [comment]
you must make clean && make gpu gain if you want use gpu in cortex
