### ISSUE TITLE
Add Fake Mode in Cuckoo Consensus for Testing

### ISSUE THREAD

**Issue by DhunterAO** [CortexFoundation/CortexTheseus#622]
The testing for core package needs a consensus engine to verify the classes like block, header, etc.
In current project, I wrote a fake engine to implement all functions for Engine interface, however, almost all of the verification functions are empty. So this can be only used to do some basic test.
1. To complete this fake engine for test, we could add a Fake mode in current Cuckoo engine, and omit some verification like PoW. The defect is that we need to solve the cycle imports, which means convert some functions like CheckGasLimit from core package into cuckoo package. So that we can import cuckoo package in core package.
2. Another choice is that we wrote a more complete fake engine in core package. The defect is we need to update 2 engines in different package, which may cause bugs for future update.

**Comment by ucwong** [comment]
Good，we can cover them with actual pow, so fake mode is not very very useful under this package for UT.
You can just skip this.
