### ISSUE TITLE
EIP related bugs

### ISSUE THREAD

**Issue by DhunterAO** [CortexFoundation/CortexTheseus#638]
In AllCuckooProtocolChanges, the EIP information is not set, which seems to cause bugs in blockchain test. Because the influence of EIP is maintained in some places like IntermediateRoot function.
Could we remove the code EIP related code?

**Comment by ucwong** [comment]
You can set all eips as zero, then all eips will be available
just like this 
```
HomesteadBlock:      big.NewInt(0),
                DAOForkBlock:        big.NewInt(0),
                DAOForkSupport:      false,
                EIP150Block:         big.NewInt(0),
                EIP150Hash:          common.HexToHash("0x"),
                EIP155Block:         big.NewInt(0),
                EIP158Block:         big.NewInt(0),
                ByzantiumBlock:      big.NewInt(0),
                ConstantinopleBlock: big.NewInt(0),
                PetersburgBlock:     big.NewInt(0),
                IstanbulBlock:       big.NewInt(0),
                Cuckoo:              new(CuckooConfig),
```
You can try this first

**Comment by ucwong** [comment]
This ```AllCuckooProtocolChanges``` is a config with all hard fork changes for testing

**Comment by DhunterAO** [comment]
Got it, I'll find out the key point

**Comment by DhunterAO** [comment]
Fixed by set EIP hashes into zero hash
