### ISSUE TITLE
Description of Quota Rules?

### ISSUE THREAD

**Issue by DhunterAO** [CortexFoundation/CortexTheseus#645]
While generate a testchain, I meet some panic of the Quota rule. So I wonder if there is a description of Quota rules? If not, maybe I can try to summary them and write into Wiki.

**Comment by ucwong** [comment]
```
BLOCK_QUOTA         = 65536       // Upon the generation of a new valid block, 64kB file quota is added to the network. Empty blocks also count.
PER_UPLOAD_BYTES       uint64 = 1 * 512 * 1024     // Step of each progress update about how many bytes per upload tx
DEFAULT_UPLOAD_BYTES   uint64 = 0                  // Default upload bytes
MODEL_MIN_UPLOAD_BYTES        = 0                  // Minimum size of a model
MODEL_MAX_UPLOAD_BYTES uint64 = 1024 * 1024 * 1024 // Maximum size of a model
```

**Comment by ucwong** [comment]
It will be very nice to add it to wiki

**Comment by ucwong** [comment]
https://github.com/CortexFoundation/tech-doc/blob/master/storage-layer.md

**Comment by DhunterAO** [comment]
https://github.com/CortexFoundation/tech-doc/pull/11
I just add the quota into a new doc. Is it better to combine these two docs?

**Comment by ucwong** [comment]
> [CortexFoundation/tech-doc#11](https://github.com/CortexFoundation/tech-doc/pull/11)
> I just add the quota into a new doc. Is it better to combine these two docs?

Keep it as a more technique one, just add it to tech-doc
