### ISSUE TITLE
common/lru(add fuction)

### ISSUE THREAD

**Issue by ShadowErii** [CortexFoundation/CortexTheseus#646]
in the add fuction,if i add a entry with very large weight, it just remove the oldest one for once time,after that,the currentweight is still bigger than the maxweight

**Comment by ucwong** [comment]
This lru used to control the model in memory, used the weight as the memory used.

Max weight (memory limit) used to invoke the Evicted,  LRU is to keep the cache hits. The weight can be bigger than max and will still trigger evict when next cache add.

You can check the code below, it will good to find some issues.
https://github.com/CortexFoundation/CortexTheseus/blob/master/inference/synapse/local_infer.go#L129-L176

```
s.caches[s.config.DeviceId].OnEvicted = func(key lru.Key, value interface{}) {
			log.Warn("C FREE On Evicted", "k", key, "size", value.(*kernel.Model).Size(), "max", s.config.MaxMemoryUsage, "min", MinMemoryUsage)
			value.(*kernel.Model).Free()
```

**Comment by ShadowErii** [comment]
ok,got it
