### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by ShadowErii** [CortexFoundation/CortexTheseus#703]
i can't compile the project sucessfully as the DOC said,i thought there may be something wrong caused by the change,so i clone the project again,but can't compiled either。
<img width="1049" alt="截屏2020-07-21 下午1 58 24" src="https://user-images.githubusercontent.com/21995734/88018572-983f4580-cb5a-11ea-969e-f8d6d0d349d1.png">

**Comment by ucwong** [comment]
Check the go version and the code branch

**Comment by ShadowErii** [comment]
> Check the go version and the code branch
> Are you using ubuntu or other systems

ubuntu

**Comment by ShadowErii** [comment]
oh, it may be caused by the go version,should i use amd64 instead of linux/386?

**Comment by ucwong** [comment]
If you want upgrade go version , you should clean pre-version first
https://golang.org/dl/go1.14.6.linux-amd64.tar.gz
