### ISSUE TITLE
Why the value of modelShape (uint64 type) may be less than 0?

### ISSUE THREAD

**Issue by DhunterAO** [CortexFoundation/CortexTheseus#722]
https://github.com/CortexFoundation/CortexTheseus/blob/1e0edf5ab8be32b0492389ddac8694eef4627a8c/core/vm/instructions.go#L651

**Comment by ucwong** [comment]
I think  ```==0``` is ok here

**Comment by DhunterAO** [comment]
> I think `==0` is ok here
> You can change and test it , if there is not issue you can create a pr for it
> 
> ps : uint64 is so big for shape, it will be a small value for uint64

ok, I'll fix it soon
