### ISSUE TITLE
cvm kernel runtime error

### ISSUE THREAD

**Issue by DevMinJong** [CortexFoundation/CortexTheseus#821]
![image](https://user-images.githubusercontent.com/48992754/98771825-a2968f80-2428-11eb-92f8-e0f50bb698e1.png)

The block synchronization was well done, but the "Gas calcurate Failed - error="cvm kernel runtime error" constantly appeared as below picture showed. 
Is there any solution for "cvm kernel runtime error"?

+ I know this log does not show up when running without 'cvm.sh'. But I want to know exact reason why it show up.

**Comment by ucwong** [comment]
./cortex

**Comment by DevMinJong** [comment]
my ctxc version v1.10.12 latest
just  I want to know exact reason why it show up.

**Comment by ucwong** [comment]
Invalid model occurred

**Comment by DevMinJong** [comment]
So it's just a ctxc core bug? Is there anything else I have to do to fix that error?

**Comment by ucwong** [comment]
No, just invalid data rejected by cortex

**Comment by DevMinJong** [comment]
If I only use daemon for deposit and withdrawal, can I ignore the error log?

**Comment by ucwong** [comment]
Off course
