### ISSUE TITLE
--miner.cuda issue (CUDA version: 11.3)

### ISSUE THREAD

**Issue by luizrrodrigues** [CortexFoundation/CortexTheseus#887]
`panic: plugin.Open("plugins/cuda_helper_for_node.so"): realpath failed`

![image](https://user-images.githubusercontent.com/7029641/107685350-aa154100-6c82-11eb-94e3-5292cdb79bf8.png)

![image](https://user-images.githubusercontent.com/7029641/107685397-b9948a00-6c82-11eb-8ef9-23cef09ef461.png)

**Comment by luizrrodrigues** [comment]
Looks like GPU miner was removed here: https://github.com/CortexFoundation/CortexTheseus/commit/cd3ed895164c497cb0956ef5fa9f40328361c035#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

**Comment by ucwong** [comment]
You should build GPU node with ``` make gpu``` for mining solo

**Comment by luizrrodrigues** [comment]
@ucwong yep, I’m so that. But keep showing this error. 

Looks like ‘make gpu’ not creating cuda plugin file anymore.

**Comment by ucwong** [comment]
```$(MAKE) -C $(BASE)/solution cuda``` should do this.
Try  ```ls plugins/*```  to check the library deps

**Comment by ucwong** [comment]
It is a good catch, thanks

**Comment by ucwong** [comment]
https://github.com/CortexFoundation/CortexTheseus/pull/899

**Comment by luizrrodrigues** [comment]
Cool, thanks @ucwong 

I had tried that before and looks like working well.

**Comment by ucwong** [comment]
It should be useful or you can try on test net, I think it will be easier for testing.

**Comment by luizrrodrigues** [comment]
@ucwong Tested in testnet and working well.

Back to mainnet and found a block:
![image](https://user-images.githubusercontent.com/7029641/109898465-0f9d9180-7c73-11eb-9f08-70319f8d10d3.png)

Confirming this working well with WSL2 (Ubuntu 20.04)

We good to close this one.

**Comment by ucwong** [comment]
Awesome @luizrrodrigues
