### ISSUE TITLE
Searching file for gas ih=0x7C6f...31c4 error="download not completed"

### ISSUE THREAD

**Issue by luizrrodrigues** [CortexFoundation/CortexTheseus#893]
![image](https://user-images.githubusercontent.com/7029641/108848658-0439ce80-75c0-11eb-88de-08b8ba39cd19.png)

`DEBUG[02-23|10:13:28.170] Gas Task                                 Model Hash=0x7C6fF2AE3b9Dfc654c5dEc61CC950b70a16431c4
DEBUG[02-23|10:13:28.170] Not ready                                ih=7c6ff2ae3b9dfc654c5dec61cc950b70a16431c4 status=4 seed=true seeding=7
DEBUG[02-23|10:13:28.170] Searching file for gas                   ih=0x7C6fF2AE3b9Dfc654c5dEc61CC950b70a16431c4 error="download not completed"`

**Comment by ucwong** [comment]
It is normal log for unfinished off chain file

**Comment by luizrrodrigues** [comment]
@ucwong but after sync this need be stop right? Already done with sync, but this keep showing (1 week running the core)

**Comment by ucwong** [comment]
> @ucwong but after sync this need be stop right? Already done with sync, but this keep showing (1 week running the core)

It seems some tx is trying to call some model file which is unavailable. You can just ignore this log on debug level.

**Comment by luizrrodrigues** [comment]
@ucwong Okay, I'll ignore this for now and reopen this if found anything related.

Just to log, if activate the `storage.boost`, boost seed will spam with this model:
`0x7C6fF2AE3b9Dfc654c5dEc61CC950b70a16431c4`

![image](https://user-images.githubusercontent.com/7029641/109853286-84051000-7c34-11eb-90cf-0a89671248a4.png)

**Comment by ucwong** [comment]
```7c6ff2ae3b9dfc654c5dec61cc950b70a16431c4``` should be an illegal torrent seed. Maybe it is not exist.

**Comment by ucwong** [comment]
I will also fix this boost issue

**Comment by luizrrodrigues** [comment]
Cool, thanks @ucwong
