### ISSUE TITLE
gpu miner build

### ISSUE THREAD

**Issue by lef-fan** [CortexFoundation/CortexTheseus#907]
make clean && make gpu mine -j$(nproc)

Run "/home/test/CortexTheseus/build/bin/cortex" to launch cortex miner.
Done building.
Run "/home/test/CortexTheseus/build/bin/cortex" to launch cortex gpu.

`WARN [03-07|05:20:56.333] Memory status                            total=31975 allowance=10658 cuda=true device=0 threads=0 algo=cuckaroo mine=false`

could you please tell me what is going wrong?

**Comment by ucwong** [comment]
It is not an ERROR

**Comment by lef-fan** [comment]
True. saw the 'mine=false' but everything is fine after all. Had to wait for downloads.
I suppose the miner is based on https://github.com/CortexFoundation/PoolMiner and there isn't any significant update. similar performance ?
thank you.

**Comment by ucwong** [comment]
I think you should start with ```--mine``` flag

**Comment by lef-fan** [comment]
I am using the --mine flag but output like above remains false. flags change for the rest of them though.

**Comment by ucwong** [comment]
show the whole boot cmd

**Comment by lef-fan** [comment]
`./build/bin/cortex --mine --miner.cuda --miner.coinbase=xxxx --miner.threads=8`

which results to: 

`WARN [03-14|10:18:25.578] Memory status                            total=31974 allowance=10658 cuda=true device=0 threads=8 algo=cuckaroo mine=false`

**Comment by ucwong** [comment]
https://github.com/CortexFoundation/CortexTheseus/commit/d6f6f251dccd3debf736c5d06515776e2028c12c
this flag has been removed for useless, thanks for this catch
