### ISSUE TITLE
Solo mining no block rewards

### ISSUE THREAD

**Issue by cryptoztimez** [CortexFoundation/CortexTheseus#911]
Linked below are 2 blocks mined Solo to the node. I have not received the mining rewards to my wallet. What is going on? 

https://cerebro.cortexlabs.ai/#/block/3404743
https://cerebro.cortexlabs.ai/#/block/3405173
https://cerebro.cortexlabs.ai/#/address/0x24cf9bccc7b42d282baf6885db9d0727a32e9a4e

**Comment by cryptoztimez** [comment]
![Screenshot 2021-03-10 044431](https://user-images.githubusercontent.com/80123070/110624735-d7f38580-815b-11eb-87b0-9d3d052d6ce3.png)
![Screenshot 2021-03-10 044525](https://user-images.githubusercontent.com/80123070/110624736-d7f38580-815b-11eb-88d5-16c8d8d244f9.png)

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/110730395-5a16a380-825b-11eb-808b-edbc2f8ae364.png)

I think rewards are OK, check the balance again

**Comment by cryptoztimez** [comment]
Still no rewards to account 
https://cerebro.cortexlabs.ai/#/address/0x24cf9bccc7b42d282baf6885db9d0727a32e9a4e

**Comment by ucwong** [comment]
No tx view for mining reward in explorer. You can contact the explore team for help

**Comment by ucwong** [comment]
The reward is added to balance

**Comment by cryptoztimez** [comment]
I don't see it my balance has been the same 130.5ctxc since 3/09/21 
Is there a certain number of confirmations needed on the blocks before mining payments are sent?

**Comment by cryptoztimez** [comment]
I did a small miscalculation on my part, the reward balance has been added. Thank you for your help @ucwong I will close this issue.
